spring:
  datasource:
    driver-class-name: ${database.driver}
    url: j${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
oauth2:
  google:
    client-id: ${google.client-id}
    client-secret: ${google.client-secret}
    authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    redirect-uri: http://localhost:8080/api/login/oauth2/code/GOOGLE
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  naver:
    client-id: ${naver.client-id}
    client-secret: ${naver.client-secret}
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: http://localhost:8080/api/login/oauth2/code/NAVER
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
jwt:
  secret-key: ${jwt.secret-key}
  refresh-key: ${jwt.refresh-key}
server:
  servlet:
    context-path: /api


